<?php 
 $TFT = array
    (
        array(
            "Personagens",
            "Aatrox",
            "Aatrox é uma personagem de ataque corpo-a-corpo, focada em causar grandes quantidades de dano em vários alvos.<br/><br/>
            Sua habilidade é causar um impacto à sua frente com sua espada, causando dano em até 4 personagens inimigos.",
            "Demonio",
            "MestreDasLaminas",
            "nada"),
        array(
            "Personagens",
            "Ahri",            
            "Ahri é uma personagem de ataque à distância, focada em causar grandes quantidades de dano em vários alvos.<br/><br/>
            Sua habilidade é arremessar um orbe de energia em linha reta que age como um bumerangue, causando dano em até 3 inimigos na ida e na volta.",
            "Selvagem",
            "Feiticeiro",
            "nada"),
        array(
            "Personagens",
            "Akali", 
            "Akali é uma personagem de ataque corpo-a-corpo, focada em causar grandes quantidades de dano em poucos alvos.<br/><br/>
            Sua habilidade é atirar kunais para frente causando enormes quantidades de dano em até 2 inimigos.",
            "Ninja",
            "Assassino",
            "nada"),
        array(
            "Personagens",
            "Anivia",
            "Anivia é uma personagem de ataque à distância, focada em causar efeitos negativos nos personagens inimigos.<br/><br/>
            Sua habilidade é criar uma tempestade de neve envolta de um inimigo aleatório, causando dano por segundo e diminuindo a velocidade de ataque dos inimigos atingidos.",
            "Glacial",
            "Elementalista",
            "nada"), 
        array(
            "Personagens",
            "Ashe",
            "Ashe é uma personagem de ataque à distância, focada em causar grandes quantidades de dano em alvo único.<br/><br/>
            Sua habilidade é atirar uma enorme flecha em direção reta, ao atingir um inimigo a flesha causa grande quantidade de dano e congela o inimigo por um determinado tempo.",
            "Glacial",
            "Patrulheiro",
            "nada"),
        array(
            "Personagens",
            "AurelionSol",
            "Aurelion Sol é uma personagem de ataque à distância, focada em causar grandes quantidades de dano em vários alvos.<br/><br/>
            Sua habilidade é atingir os inimigos com uma poderosa cólera que causa enormes quantidades de dano em um grande espaço à sua frente, atingindo até 8 inimigos.",
            "Dragao",
            "Feiticeiro",
            "nada"), 
        array(
            "Personagens",
            "Blitzcrank",
            "Blitzcranck é uma personagem de ataque corpo-a-corpo, focada em expor personagens vulneráveis do time inimigo e alterar o foco dos demais personagens.<br/><br/>
            Sua habilidade é puxar o inimigo mais distante para sua frente e arremessá-lo ao ar.",
            "Robo",
            "Lutador",
            "nada"), 
        array(
            "Personagens",
            "Brand",
            "Brand é uma personagem de ataque à distância, focada em causar grandes quantidades de dano em vários alvos.<br/><br/>
            Sua habilidade é arremessar uma bola de fogo em um inimigo que saltará para inimigos próximos, causando dano à cada salto.",
            "Demonio",
            "Elementalista",
            "nada"),         
        array(
            "Personagens",
            "Braum",
            "Braum é uma personagem de ataque corpo-a-corpo, focada em atrair todo o dano para si e resistir ao mesmo.<br/><br/>
            Sua habilidade é erguer um poderoso escudo de gelo que diminui a porcentagem de dano que ele recebe.",
            "Glacial",
            "Guardiao",
            "nada"),        
        array(
            "Personagens",
            "Chogath",
            "Cho'Gath é uma personagem de ataque corpo-a-corpo, focada em desabilitar o time inimigo durante um período de tempo.<br/><br/>
            Sua habilidade é causr uma erupção de espinhos vinda do solo, elevando todos os oponentes atingidos ao ar.",
            "Vastinata",
            "Lutador",
            "nada"),        
        array(
            "Personagens",
            "Darius",
            "Darius é uma personagem de ataque corpo-a-corpo, focada em atrair todo o dano para si e resistir ao mesmo.<br/><br/>
            Sua habilidade é girar seu machado, causando dano nos inimigos ao seu redor e curando-se em uma porção do dano causado.",
            "Imperial",
            "Cavaleiro",
            "nada"),
        array(
            "Personagens",
            "Draven",
            "Draven é uma personagem de ataque à distância, focada em causar grandes quantidades de dano em alvos únicos.<br/><br/>
            Sua habilidade é girar seus machados antes de arremessá-los contra o inimigo, desta maneira aumentando, consideravelmente, seu dano.",
            "Imperial",
            "MestreDasLaminas",
            "nada"),
        array(
            "Personagens",
            "Elise",
            "Elise é uma personagem de ataque à distância, focada em distrair os inimigos com alvos não importantes.<br/><br/>
            Sua habilidade é se transformar em uma aranha gigante, aumentando seu dano, enquanto invoca suas crias para atacar os inimigos, as crias são consideradas como mais um personagem aliado.",
            "Demonio",
            "Metamorfo",
            "nada"),
        array(
            "Personagens",
            "Evelynn",
            "Evelynn é uma personagem de ataque corpo-a-corpo, focada em causar grandes quantidades de dano em vários alvos.<br/><br/>
            Sua habilidade é liberar seu poder demoníaco, dizimando os inimigos em sua frente enquanto torna-se inalvejável e move-se para trás.",
            "Demonio",
            "Assassino",
            "nada"), 
        array(
            "Personagens",
            "Fiora",
            "Fiora é uma personagem de ataque corpo-a-corpo, focada em atrair todo o dano para si e resistir ao mesmo.<br/><br/>
            Sua habilidade é preparar um contra-ataque, não recebendo nenhum dano enquanto o prepara, ao liberar o contra-ataque, causa dano e atordoa um inimigo.",
            "Nobre",
            "MestreDasLaminas",
            "nada"),
        array(
            "Personagens",
            "Gangplank",
            "Gangplank é uma personagem de ataque corpo-a-corpo, focada em causar dano em diversos inimigos.<br/><br/>
            Sua habilidade é espalhar seus barris de pólvora, aleatoriamente, pelo mapa. Ao lançar seu 3º barril, ele atira contra um deles, explodindo os mesmos em uma reação em cadeia.",
            "Pirata",
            "MestreDasLaminas",
            "Pistoleiro"), 
        array(
            "Personagens",
            "Garen",
            "Garen é uma personagem de ataque corpo-a-corpo, focada em atrair todo o dano para si e resistir ao mesmo.<br/><br/>
            Sua habilidade é girar sua espada em torno de si inúmeras vezes, causando dano aos inimigos ao seu redor e tornando-se imune ao dano de habilidades.",
            "Nobre",
            "Cavaleiro",
            "nada"), 
        array(
            "Personagens",
            "Gnar",
            "Gnar é uma personagem de ataque corpo-a-corpo, focada em desabilitar os personagens do time inimigo.<br/><br/>
            Sua habilidade é libertar sua fúria, transformando-se um monstro, pulando contra os inimigos e arremessando-os para uma direção específica, atordoando-os no processo.",
            "Selvagem",
            "Yordle",
            "Metamorfo"),         
        array(
            "Personagens",
            "Graves",
            "Graves é uma personagem de ataque corpo-a-corpo, focada em causar dano em diversos inimigos.<br/><br/>
            Sua habilidade é fazer com que seus ataques básicos atinjam todos os inimigos numa área de cone à sua frente. Esta habilidade é passiva e mantêm-se ativa durante todo o jogo.",
            "Pirata",
            "Pistoleiro",
            "nada"),        
        array(
            "Personagens",
            "Karthus",
            "Karthus é uma personagem de ataque à distãncia, focada em causar grandes quantidades de dano em diversos inimigos.<br/><br/>
            Sua habilidade é convocar o poder de almas atormentadas para causarem dano direto em diversos inimigos, após uma canalização de alguns segundos.",
            "Fantasma",
            "Feiticeiro",
            "nada"),        
        array(
            "Personagens",
            "Kassadin",
            "Kassadin é uma personagem de ataque corpo-a-corpo, focada em impedir que os demais personagens utilizem suas habilidades.<br/><br/>
            Sua habilidade é drenar os pontos de mana dos inimigos atingidos por seus ataques básicos, convertendo parte desta mana em um escudo. Esta habilidade é passiva e mantêm-se ativa durante todo o jogo",
            "Vastinata",
            "Feiticeiro",
            "nada"),
        array(
            "Personagens",
            "Katarina",
            "Katarina é uma personagem de ataque corpo-a-corpo, focada em causar dano em diversos inimigos e impedir que os mesmos se curem.<br/><br/>
            Sua habilidade é atirar diversas adagas diretamente contra alguns inimigos, causando dano contínuo e impedindo que este inimigo recupere seus pontos de vida.",
            "Imperial",
            "Assassino",
            "nada",),
        array(
            "Personagens",
            "Kayle",
            "Kayle é uma personagem de ataque à distância, focada em proteger seus aliados.<br/><br/>
            Sua habilidade é criar um escudo divino para proteger alguns aliados contra todo o dano recebido.",
            "Nobre",
            "Cavaleiro",
            "nada"),
        array(
            "Personagens",
            "Kennen",
            "Kennen é uma personagem de ataque à distância, focada em causar dano em área e imobilizar os inimigos.<br/><br/>
            Sua habilidade é criar uma tempestade de raios ao seu redor, fazendo com que 3 raios caiam contra cada inimigo na área. Cada raio causa dano e, ao acertar os 3, o inimigo é atordoado.",
            "Ninja",
            "Yordle",
            "Elementalista"), 
        array(
            "Personagens",
            "Khazix",
            "Kha'Zix é uma personagem de ataque corpo-a-corpo, focada em causar muito dano contra um alvo único.<br/><br/>
            Sua habilidade é golpear um único alvo com suas garras, causando uma enorme quantidade de dano. Se o alvo estiver isolado, este dano é aumentado.",
            "Vastinata",
            "Assassino",
            "nada"),
        array(
            "Personagens",
            "Kindred",
            "Kindred é uma personagem de ataque à distância, focada em proteger seus aliados.<br/><br/>
            Sua habilidade é criar um refúgio para os aliados, onde nenhum deles pode morrer durante um período de tempo.",
            "Fantasma",
            "Patrulheiro",
            "nada"), 
        array(
            "Personagens",
            "Leona",
            "Leona é uma personagem de ataque corpo-a-corpo, focada em atrair todo o dano para si e resistir ao mesmo e desabilitar um personagem inimigo.<br/><br/>
            Sua habilidade é lançar um feixe de luz solar contra um alvo inimigo, atordoando este alvo durante um longo período.",
            "Nobre",
            "Guardiao",
            "nada"), 
        array(
            "Personagens",
            "Lissandra",
            "Lissandra é uma personagem de ataque à distância, focada em desabilitar um personagem inimigo.<br/><br/>
            Sua habilidade é convocar os poderes do gelo para congelar um alvo único, caso esteja com muitos pontos de vida. Caso esteja prestes a morrer, conjura o gelo em si mesma para se proteger de todo o dano, mas fica imóvel no processo.",
            "Glacial",
            "Elementalista",
            "nada"),         
        array(
            "Personagens",
            "Lucian",
            "Lucian é uma personagem de ataque à distância, focada em causar dano em alvos únicos e evitar o dano recebido.<br/><br/>
            Sua habilidade é avançar para um local aleatório, dando dois tiros subsequentes com suas pistolas no inimigo que estiver alvejando.",
            "Nobre",
            "Pistoleiro",
            "nada"),        
        array(
            "Personagens",
            "Lulu",
            "Lulu é uma personagem de ataque à distância, focada em proteger seus aliados.<br/><br/>
            Sua habilidade é encantar alguns personagens aliados com o poder da floresta, fazendo com que eles fiquem maiores e requperem um pouco de vida.",
            "Yordle",
            "Feiticeiro",
            "nada"),        
        array(
            "Personagens",
            "MissFortune",
            "Miss Fortune é uma personagem de ataque à distância, focada em causar muito dano contra diversos inimigos.<br/><br/>
            Sua habilidade é disparar uma constante rajada de tiros em uma grande área, na forma de um cone, à sua frente.",
            "Pirata",
            "Pistoleiro",
            "nada"),
        array(
            "Personagens",
            "Mordekaiser",
            "Mordekaiser é uma personagem de ataque corpo-a-corpo, focada em atrair todo o dano para si e resistir ao mesmo.<br/><br/>
            Sua habilidade é bater com sua maça de guerra contra os inimigos à sua frente, almejando até 2 inimigos, caso estejam aliados.",
            "Fantasma",
            "Cavaleiro",
            "nada"),
        array(
            "Personagens",
            "Morgana",
            "Morgana é uma personagem de ataque à distância, focada em causar muito dano em diversos inimigos e atordoá-los por um período.<br/><br/>
            Sua habilidade é aprisionar os inimigos ao redor em correntes negras, causando dano ao acorrentá-los. Após um certo período, as correntes estouram e os inimigos amarrados são atordoados.",
            "Demonio",
            "Feiticeiro",
            "nada"),
        array(
            "Personagens",
            "Nidalee",
            "Nidalee é uma personagem de ataque à distância, focada em causar dano em alvos únicos e resistir maior tempo em batalha.<br/><br/>
            Sua habilidade é transformar-se em um puma, aumentando seu dano de ataque e curando a si mesma e a um aliado qualquer ao decorrer do tempo.",
            "Selvagem",
            "Metamorfo",
            "nada"), 
        array(
            "Personagens",
            "Poppy",
            "Poppy é uma personagem de ataque corpo-a-corpo, focada em desabilitar os inimigos.<br/><br/>
            Sua habilidade é arremessar um golpe com seu martelo contra o chão, gerando uma elevação na terra que lança os inimigos ao ar, atordoando-os por um período.",
            "Yordle",
            "Cavaleiro",
            "nada"),
        array(
            "Personagens",
            "Pyke",
            "Pyke é uma personagem de ataque corpo-a-corpo, focada em desabilitar os inimigos por um período.<br/><br/>
            Sua habilidade é avançar para um local do mapa deixando para trás um fantasma de si mesmo, após alguns segundos o fantasma acompanha Pyke, atordoando e causando dano em todos os inimigos no caminho.",
            "Pirata",
            "Assassino",
            "nada"), 
        array(
            "Personagens",
            "RekSai",
            "Rek'Sai é uma personagem de ataque corpo-a-corpo, focada em desabilitar um personagem inimigo.<br/><br/>
            Sua habilidade é afundar na terra, avançando por debaixo do solo para as costas do inimigo e curando-se enquanto faz isso. Ao ressurgir, eleva o inimigo ao ar, atordoando-o por um certo período.",
            "Vastinata",
            "Lutador",
            "nada"), 
        array(
            "Personagens",
            "Rengar",
            "Rengar é uma personagem de ataque corpo-a-corpo, focada em causar muito dano em alvos únicos.<br/><br/>
            Sua habilidade é avançar contra um inimigo aleatório, causando grande grande quantidade de dano e aumentando a velocidade de seus ataques.",
            "Selvagem",
            "Assassino",
            "nada"),         
        array(
            "Personagens",
            "Sejuani",
            "Sejuani é uma personagem de ataque corpo-a-corpo, focada em desabilitar o time inimigo.<br/><br/>
            Sua habilidade é lançar sua maça de gelo contra os inimigos, gerando uma área congelante que, depois de uns segundos, explode, congelando todos os inimigos na área.",
            "Glacial",
            "Cavaleiro",
            "nada"),        
        array(
            "Personagens",
            "Shen",
            "Shen é uma personagem de ataque corpo-a-corpo, focada em atrair todo o dano para si e resistir ao mesmo.<br/><br/>
            Sua habilidade é conjurar um campo espiritual em sua volta, que faz com que ele e os aliados próximos não recebam dano de ataques básicos.",
            "Ninja",
            "MestreDasLaminas",
            "nada"),
        array(
            "Personagens",
            "Shyvana",
            "Shyvana é uma personagem de ataque corpo-a-corpo, focada em causar grande quantidade de dano em alvos únicos.<br/><br/>
            Sua habilidade é transformar-se em um dragão, assumindo sua forma verdadeira, passando a dar muito dano com seus ataques básicos e incendiar os inimigos com os mesmos.",
            "Dragao",
            "Metamorfo",
            "nada"),        
        array(
            "Personagens",
            "Swain",
            "Swain é uma personagem de ataque à distância, focada em atrair todo o dano para si e resistir ao mesmo, enquanto causa bastante dano em área.<br/><br/>
            Sua habilidade é liberar seu poder demoníaco, assumindo asas de corvo e drenando a vida dos inimigos próximos. Ao passar de um certo tempo, a transformação acaba com uma onda de choque, causando muito dano em sua volta.",
            "Imperial",
            "Demonio",
            "Metamorfo"),
        array(
            "Personagens",
            "Tristana",
            "Tristana é uma personagem de ataque à distância, focada em causar muito dano em alvos únicos.<br/><br/>
            Sua habilidade é grudar uma bomba em um inimigo, que é melhorada a cada ataque básico que Tristana dá contra o inimigo. Após 5 ataques básicos, a bomba explode, causando muito dano em volta do campeão com a bomba.",
            "Yordle",
            "Pistoleiro",
            "nada"),
        array(
            "Personagens",
            "TwistedFate",
            "Twisted Fate é uma personagem de ataque à distância, focada em causar dano em área, dar suporte aos aliados e imobilizar um inimigo.<br/><br/>
            Sua habilidade é scolher uma carta aleatória dentro de seu deck, a carta azul, dourada ou vermelha, cada uma com um efeito diferente.<br/> 
            A carta vermelha causa dano em área.<br/> 
            A carta azul recupera os pontos de mana de seus aliados.<br/>
            A carta dourada atordoa um inimigo.",
            "Pirata",
            "Feiticeiro",
            "nada"),
        array(
            "Personagens",
            "Varus",
            "Varus é uma personagem de ataque à distância, focada em causar muito dano em diversos inimigos.<br/><br/>
            Sua habilidade é atirar uma flecha perfurante em linha reta, que atravessa todos os inimigos no caminho, causando muito dano.",
            "Demonio",
            "Patrulheiro",
            "nada"), 
        array(
            "Personagens",
            "Vayne",
            "Vayne é uma personagem de ataque à distância, focada em causar muito dano em alvos únicos.<br/><br/>
            Sua habilidade é causar um dano extra, baseado na vida total do alvo, à cada 3 ataques básicos contra o mesmo alvo. Esta habilidade é passiva e mantêm-se ativa durante todo o jogo.",
            "Nobre",
            "Patrulheiro",
            "nada"),
        array(
            "Personagens",
            "Veigar",
            "Veigar é uma personagem de ataque à distância, focada em causar muito dano em alvos únicos.<br/><br/>
            Sua habilidade é arremessar uma poderosa bola de magia contra um inimigo aleatório, causando grandes quantidades de dano contra o mesmo. Caso o inimigo esteja em um nível inferior à Veigar, a habilidade o matará, independente de sua vida restante.",
            "Yordle",
            "Feiticeiro",
            "nada"), 
        array(
            "Personagens",
            "Volibear",
            "Volibear é uma personagem de ataque corpo-a-corpo, focada em causar dano contra diversos alvos.<br/><br/>
            Sua habilidade é convocar o poder das tempestades em suas patas, desencadeando uma cadeia de raios à cada ataque básico que desfere contra seu inimigo. Os raios se espalham pelos inimigos próximos, causando dano em todos os atingidos.",
            "Glacial",
            "Lutador",
            "nada"), 
        array(
            "Personagens",
            "Warwick",
            "Warwick é uma personagem de ataque corpo-a-corpo, focada em atordoar um alvo único.<br/><br/>
            Sua habilidade é acançar contra um inimigo, suprimindo-o com constantes ataques com suas garras. Durante este ataque o inimigo não pode se mover nem atacar.",
            "Selvagem",
            "Lutador",
            "nada"),         
        array(
            "Personagens",
            "Yasuo",
            "Yasuo é uma personagem de ataque corpo-a-corpo, focada em causar dano contra diversos alvos e imobilizá-los.<br/><br/>
            Sua habilidade é desferir um golpe horizontal com sua katana, em linha reta à sua frente. Após executar 2 vezes sua habilidade, Yasuo é envolto pelos poderes do vento, que fazem com que sua próxima habilidade conjure um tufão que segue em linha reta elevando todos os inimigos atingidos ao ar.",
            "Exilado",
            "MestreDasLaminas",
            "nada"),        
        array(
            "Personagens",
            "Zed",
            "Zed é uma personagem de ataque corpo-a-corpo, focada em causar dano contra alvos únicos.<br/><br/>
            Sua habilidade é atirar duas shurikens em linha reta, causando dano contra até 2 inimigos no caminho.",
            "Ninja",
            "Assassino",
            "nada"),        
        array(
            "Itens",
            "ArcoRecurvo",
            "Garante um aumento de 20% na velocidade de ataque do personagem.",
            "CanhaoFumegante",
            "Dobra o alcance de ataque do usuário.",
            "LaminaDaFuriaDeGuinsoo",
            "Cada ataque desferido contra um inimigo aumenta em 4% a velcidade de ataque do usuário. Aumentando infinitamente.",
            "LaminaAmaldicoada",
            "Os ataques do usuário possuem uma chance de diminuir o nível do inimigo atingido.",
            "HidraTitanica",
            "Os ataques do usuário causam um dano em área no formato de cone. Este dano corresponde à 10% da vida do usuáio.",
            "DancarinaFantasma",
            "O usuário desvia de todos os acertos críticos desferidos contra ele.",
            "EspadaDoDivino",
            "A cada segundo existe uma chance de 5% de o usuário ganhar 100% de chance de acerto crítico até o final da rodada.",
            "EspandaDoReiDestruido",
            "O usuário deste item passa a ser considerado um Mestre das Lâminas.",
            "FacaDeStatikk",
            "A cada 3 ataques básicos do usuário, um raio é desencadeado entre 3 inimigos, causando 100 de dano mágico à cada um deles."),
        array(
            "Itens",
            "BastaoDesnecessariamenteGrande",
            "Garante um aumento de 20% no dano de habilidades.",
            "LaminaDaFuriaDeGuinsoo",
            "Cada ataque desferido contra um inimigo aumenta em 4% a velcidade de ataque do usuário. Aumentando infinitamente.",
            "CapuzDaMorteDeRabadon",
            "Aumenta em 50% o dano de habilidade do usuário",
            "CentelhaIonica",
            "Quando um inimigo usar sua habilidade, um raio será desferido contra ele, causando 200 de dano verdadeiro.",
            "Morellonomicon",
            "As habilidades do usuário passam a causar queimaduras, que causam 5% da vida do alvo como dano mágico por segundo e impedem que o mesmo se cure.",
            "MedalhaoDosSolariDeFerro",
            "No início de todos os confrontos, 2 aliados à esqueda e 2 aliados à direita receberão 200 pontos de escudo.",
            "PistolaLaminarHextec",
            "O usuário se cura à um equivalente de 25% do dano causado.",
            "Yuumi",
            "O usuário deste item passa a ser considerado um Feiticeiro.",
            "EcoDeLuden",
            "As habilidades do usuário ecoam poder mágico dentre os inimigos próximos, causando 200 de dano mágico à cada inimigo atingido."), 
        array(
            "Itens",
            "CapaNegatron",
            "Garante um aumento de 20 pontos na resistência ao dano de habilidades.",
            "LaminaAmaldicoada",
            "Os ataques do usuário possuem uma chance de diminuir o nível do inimigo atingido.",
            "CentelhaIonica",
            "Quando um inimigo usar sua habilidade, um raio será desferido contra ele, causando 200 de dano verdadeiro.",
            "GarraDoDragao",
            "O usuário recebe 83% de resistência contra o dano de habilidades.",
            "Zefiro",
            "No começo de cada confronto um tornado banirá um dos inimigos por 5 segundos.",
            "QuebraEspada",
            "Os ataques do usuário possuem uma chance de desarmar o inimigo atingido. (Desarmar - Impossibilita o inimigo de desferir ataques básicos durante 3 segundos).",
            "SedentaPorSangue",
            "50% do dano causado pelos ataques básicos do usuários são convertidos em vida.",
            "FuracaoDeRunaan",
            "Uma flecha fantasma dispara contra um inimigo enquanto o usuário ataca outro. A flecha fantasma causa 25% do dano do usuário e pode aplicar efeitos de acerto.",
            "Quietude",
            "Os ataques do usuário possuem uma chance de silenciar o inimigo atingido. (Silenciar - Impossibilita o inimigo de utilizar habilidades durante 4 segundos)."),
        array(
            "Itens",
            "CintoDoGigante",
            "Garante um aumento de 200 pontos nos pontos de vida.",
            "HidraTitanica",
            "Os ataques do usuário causam um dano em área no formato de cone. Este dano corresponde à 10% da vida do usuáio.",
            "Morellonomicon",
            "As habilidades do usuário passam a causar queimaduras, que causam 5% da vida do alvo como dano mágico por segundo e impedem que o mesmo se cure.",
            "Zefiro",
            "No começo de cada confronto um tornado banirá um dos inimigos por 5 segundos.",
            "ArmaduraDeWarmog",
            "O usuário recupera 6% de sua vida perdida por segundo.",
            "EfeitoVermelho",
            "Ataques básicos aplicam queimaduras contra os inimigos, causando 2,5% de suas vidas em dano por segundo e impedindo que eles se curem.",
            "ArautoDeZeke",
            "No início de todos os confrontos, 2 aliados à esqueda e 2 aliados à direita receberão 15% de velocidade de ataque.",
            "MalhoCongelado",
            "O usuário deste item passa a ser considerado um Glacial.",
            "Redencao",
            "Assim que a vida do usuário se reduzir a 25% de seu máximo, uma benção divina cai sob os céus, curando todos os aliados próximos em 1000 pontos de vida."), 
        array(
            "Itens",
            "CotaDeMalha",
            "Garante um aumento de 20 pontos na resistência ao dano de ataques básicos.",
            "DancarinaFantasma",
            "O usuário desvia de todos os acertos críticos desferidos contra ele.",
            "MedalhaoDosSolariDeFerro",
            "No início de todos os confrontos, 2 aliados à esqueda e 2 aliados à direita receberão 200 pontos de escudo.",
            "QuebraEspada",
            "Os ataques do usuário possuem uma chance de desarmar o inimigo atingido. (Desarmar - Impossibilita o inimigo de desferir ataques básicos durante 3 segundos).",
            "EfeitoVermelho",
            "Ataques básicos aplicam queimaduras contra os inimigos, causando 2,5% de suas vidas em dano por segundo e impedindo que eles se curem.",
            "ArmaduraDeEspinhos",
            "Todo o dano de ataques básicos causado contra o usuário é refletido de maneira mitigada.",
            "AnjoGuardiao",
            "Quando o usuário morre, volta a vida com 1000 pontos de vida.",
            "JuramentoDoCavaleiro",
            "O usuário deste item passa a ser considerado um Cavaleiro.",
            "CoracaoCongelado",
            "Os inimigos próximos do usuário deste item têm sua velocidade de ataque reduzida em 20%."), 
        array(
            "Itens",
            "EspadaG.p.C.",
            "Garante um aumento de 20 pontos no dano de ataques básicos.",
            "EspadaDoDivino",
            "A cada segundo existe uma chance de 5% de o usuário ganhar 100% de chance de acerto crítico até o final da rodada.",
            "PistolaLaminarHextec",
            "O usuário se cura à um equivalente de 25% do dano causado.",
            "SedentaPorSangue",
            "50% do dano causado pelos ataques básicos do usuários são convertidos em vida.",
            "ArautoDeZeke",
            "No início de todos os confrontos, 2 aliados à esqueda e 2 aliados à direita receberão 15% de velocidade de ataque.",
            "AnjoGuardiao",
            "Quando o usuário morre, volta a vida com 1000 pontos de vida.",
            "GumeDoInfinito",
            "Acertos críticos causados pelo usuário causam 150% a mais de dano.",
            "LaminaFantasmaDeYoumuu",
            "O usuário deste item passa a ser considerado um Assassino.",
            "LancaDeShojin",
            "Após utilizar sua habilidade, os ataques básicos consederão 15% a mais dos pontos de mana máxima para o usuáio."),         
        array(
            "Itens",
            "Espatula",
            "Dobra o efeito garantido pelo item com o qual se fundir.",
            "EspandaDoReiDestruido",
            "O usuário deste item passa a ser considerado um Mestre das Lâminas.",
            "Yuumi",
            "O usuário deste item passa a ser considerado um Feiticeiro.",
            "FuracaoDeRunaan",
            "Uma flecha fantasma dispara contra um inimigo enquanto o usuário ataca outro. A flecha fantasma causa 25% do dano do usuário e pode aplicar efeitos de acerto.",
            "MalhoCongelado",
            "O usuário deste item passa a ser considerado um Glacial.",
            "JuramentoDoCavaleiro",
            "O usuário deste item passa a ser considerado um Cavaleiro.",
            "LaminaFantasmaDeYoumuu",
            "O usuário deste item passa a ser considerado um Assassino.",
            "ForcaDaNatureza",
            "Quando este item é equipado em algum personagem, um espaço a mais no campo de batalha é liberado.",
            "Darkin",
            "O usuário deste item passa a ser considerado um Demônio."),        
        array(
            "Itens",
            "LagrimaDaDeusa",
            "Garante um aumento de 20 pontos nos pontos de mana.",
            "FacaDeStatikk",
            "A cada 3 ataques básicos do usuário, um raio é desencadeado entre 3 inimigos, causando 100 de dano mágico à cada um deles.",
            "EcoDeLuden",
            "As habilidades do usuário ecoam poder mágico dentre os inimigos próximos, causando 200 de dano mágico à cada inimigo atingido.",
            "Quietude",
            "Os ataques do usuário possuem uma chance de silenciar o inimigo atingido. (Silenciar - Impossibilita o inimigo de utilizar habilidades durante 4 segundos).",
            "Redencao",
            "Assim que a vida do usuário se reduzir a 25% de seu máximo, uma benção divina cai sob os céus, curando todos os aliados próximos em 1000 pontos de vida.",
            "CoracaoCongelado",
            "Os inimigos próximos do usuário deste item têm sua velocidade de ataque reduzida em 20%.",
            "LancaDeShojin",
            "Após utilizar sua habilidade, os ataques básicos consederão 15% a mais dos pontos de mana máxima para o usuáio.",
            "Darkin",
            "O usuário deste item passa a ser considerado um Demônio.",
            "AbracoDeSeraph",
            "Sempre que o usuário utilizar sua habilidade, são recuperados, instantaneamente, 20 pontos de mana."),
        array(
            "Origens",
            "Demonio",
            "Demônios possuem uma chance de queimar uma parte dos pontos de mana de seus inimigos, causando dano extra no processo.<br/><br/>
            2 Demônios - 25% de chance;<br/>
            4 Demõnios - 50% de chance;<br/>
            6 Demônios - 85% de chance."),
        array(
            "Origens",
            "Dragao",
            "Quando dois dragões aliados são reunidos em campo, recebem um escudo que bloqueia todo o dano de habilidades inimigas."), 
        array(
            "Origens",
            "Exilado",
            "Se um exilado for colocado em uma posição isolada de seus aliados, ganha um escudo equivalente à 100% de sua vida.",
            "https://img.ibxk.com.br///2018/09/06/06164716963170-t1200x480.jpg"),
        array(
            "Origens",
            "Fantasma",
            "Quando 2 fantasmas são reunidos em campo, eles amaldiçoam um inimigo aleatório no começo de toda partida, fazendo com que sua vida seja reduzida à 100 pontos.",
            "https://img.ibxk.com.br//2018/09/10/10114525136032-t1200x480.jpg"), 
        array(
            "Origens",
            "Glacial",
            "Glaciais possuem uma chance de congelar seus inimigos com seus ataques básicos.<br/><br/>
            2 Demônios - 20% de chance;<br/>
            4 Demõnios - 30% de chance;<br/>
            6 Demônios - 45% de chance.",
            "https://img.ibxk.com.br//2018/09/11/11082313062008-t1200x480.jpg"), 
        array(
            "Origens",
            "Imperial",
            "Imperiais possuem seu dano dobrado.<br/><br/>
            2 Imperiais - Efeito concebido a um imperial aleatório;<br/>
            4 Imperiais - Efeito concebido a todos os imperiais em campo.",
            "https://img.ibxk.com.br///2018/09/01/01233103985046-t1200x480.jpg"),         
        array(
            "Origens",
            "Ninja",
            "Ninjas só recebem seus efeitos quando 1 ninja está sozinho, ou quando os 4 estão juntos.<br/><br/>
            1 Ninja - 40% a mais de dano;<br/>
            4 Ninjas - 80% a mais de dano",
            "https://img.ibxk.com.br///2017/12/13/13094649516017-t1200x480.jpg"),        
        array(
            "Origens",
            "Nobre",
            "Personagens recebem 100 pontos de armadura e passam a curar 35 de pontos de vida à cada ataque básico.<br/><br/>
            3 Nobres - 1 personagem aleatório recebe o efeito;<br/>
            6 Nobres - Todos os personagens em campo recebem o efeito.",
            "https://img.ibxk.com.br///2017/12/13/13094649516017-t1200x480.jpg"),
        array(
            "Origens",
            "Pirata",
            "Quando 3 piratas se reúnem em campo, recebem um baú de ouro ao fim de confrontos, que pode conter até 4 moedas",
            "https://img.ibxk.com.br///2018/09/11/11094753717002-t1200x480.jpg"),
        array(
            "Origens",
            "Robo",
            "Todos os robôs começam a partida com 100% de pontos de mana.",
            "https://img.ibxk.com.br///2018/09/10/10175905080123-t1200x480.jpg"), 
        array(
            "Origens",
            "Selvagem",
            "Cada ataque básico gera um ponto de fúria, que acumulam-se até 5 pontos. Cada ponto de fúria aumenta em 10% a velocidade de ataque.<br/><br/>
            2 Selvagens - Todos os selvagens recebem o efeito;<br/>
            4 Selvagens - Todos os aliados recebem o efeito.",
            "https://img.ibxk.com.br///2018/09/06/06164716963170-t1200x480.jpg"),
        array(
            "Origens",
            "Vastinata",
            "Quando 3 vastinatas se reúnem em campo, todo o dano causado por eles passa a ser dano verdadeiro.",
            "https://img.ibxk.com.br//2018/09/10/10114525136032-t1200x480.jpg"), 
        array(
            "Origens",
            "Yordle",
            "Ataques desferidos contra um Yordle possuem uma chance de errar.<br/><br/>
            3 Yordles - 25% de chance;<br/>
            6 Yordles - 60% de chance.",
            "https://img.ibxk.com.br//2018/09/11/11082313062008-t1200x480.jpg"), 
        array(
            "Classes",
            "Assassino",
            "Ao começo de todos os confrontos, assassinos pulam, de maneira furtiva, para as costas do inimigo mais distante, e causam um porcentual de dano a mais em seus ataques críticos.<br/><br/>
            3 Assassinos - 125% a mais de dano crítico;<br/>
            6 Assassinos - 350% a mais de dano crítico.",
            "https://img.ibxk.com.br///2018/09/01/01233103985046-t1200x480.jpg"),         
        array(
            "Classes",
            "Cavaleiro",
            "Cavaleiros bloquieam parte do dano recebido de ataques básicos.<br/><br/>
            2 Cavaleiros - 20 de dano bloqueado;<br/>
            4 Cavaleiros - 40 de dano bloqueado;<br/>
            6 Cavaleiros - 80 de dano bloqueado.",
            "https://img.ibxk.com.br///2017/12/13/13094649516017-t1200x480.jpg"),        
        array(
            "Classes",
            "Elementalista",
            "Elementalistas recebem o dobro de pontos de mana por ataque, e quando 3 deles se reúnem em campo, um Golem é invocado.",
            "https://img.ibxk.com.br///2017/12/13/13094649516017-t1200x480.jpg"),
        array(
            "Classes",
            "Feiticeiro",
            "Feiticeiros recebem o dobro de pontos de mana por ataque e aumentam o dano das habilidades de sua equipe.<br/><br/>
            3 Feiticeiros - 45% a mais de dano de habilidades;<br/>
            6 Feiticeiros - 100% a mais de dano de habilidades.",
            "https://img.ibxk.com.br///2018/09/10/10175905080123-t1200x480.jpg"), 
        array(
            "Classes",
            "Guardiao",
            "Quando 2 guardiões se reúnem eles e seus aliados próximos recebem 40 a mais de armadura.",
            "https://img.ibxk.com.br///2018/09/06/06164716963170-t1200x480.jpg"),
        array(
            "Classes",
            "Lutador",
            "Lutadores recebem uma parcela a mais de pontos de vida.<br/><br/>
            2 Lutadores - 300 a mais de vida;<br/>
            4 Lutadores - 700 a mais de vida.",
            "https://img.ibxk.com.br//2018/09/10/10114525136032-t1200x480.jpg"), 
        array(
            "Classes",
            "MestreDasLaminas",
            "Mestres das Lâminas possuem 35% de chance de desferirem ataques adicionais contra seus inimigos.<br/><br/>
            3 Mestres das Lâminas - 1 ataques adicionais;<br/>
            6 Mestres das Lâminas - 2 ataques adicionais.",
            "https://img.ibxk.com.br//2018/09/11/11082313062008-t1200x480.jpg"), 
        array(
            "Classes",
            "Metamorfo",
            "Quando 3 metamorfos se reúnem em campo, passam a receber 60% a mais de pontos de vida máxima quando se transformam.",
            "https://img.ibxk.com.br///2018/09/01/01233103985046-t1200x480.jpg"),         
        array(
            "Classes",
            "Patrulheiro",
            "Patrulheiros possuem uma chance de dobrar suas velocidades de ataque durante 3 segundos.<br/><br/>
            2 Patrulheiros - 25% de chance;<br/>
            4 Patrulheiros - 65% de chance.",
            "https://img.ibxk.com.br///2017/12/13/13094649516017-t1200x480.jpg"),      
        array(
            "Classes",
            "Pistoleiro",
            "Pistoleiros possuem 50% de chance de desferirem ataques adicionais a alvos diferentes.<br/><br/>
            2 Pistoleiros - Atacam 1 alvo diferente;<br/>
            4 Pistoleiros - Atacam 2 alvos diferentes.",
            "https://img.ibxk.com.br///2017/12/13/13094649516017-t1200x480.jpg"),
    ); 
?>